import { Order, Packet, PacketName, Rarity } from '@/types';

const mewPacket: Packet = {
  name: PacketName.MEW,
  subPackets: [
    {
      order: Order.FIRST_TO_THIRD,
      bundles: [
        {
          rarity: Rarity.DIAMOND1,
          probability: 100.0,
          cards: [
            'Exeggcute',
            'Snivy',
            'Morelull',
            'Ponyta',
            'Larvesta',
            'Salandit',
            'Salazzle',
            'Magikarp',
            'Finneon',
            'Chewtle',
            'Cramorant',
            'Pikachu',
            'Joltik',
            'Dedenne',
            'Elgyem',
            'Swirlix',
            'Flabébé',
            'Floette',
            'Slurpuff',
            'Mankey',
            'Primeape',
            'Geodude',
            'Koffing',
            'Purrloin',
            'Liepard',
            'Venipede',
            'Whirlipede',
            'Pidgey',
            'Pidgeotto',
            'Eevee',
            'Chatot',
            'Old Amber',
          ],
        },
      ],
    },
    {
      order: Order.FOURTH,
      bundles: [
        {
          rarity: Rarity.CROWN,
          probability: 0.04,
          cards: ['Mew ex'],
        },
        {
          rarity: Rarity.STAR3,
          probability: 0.222,
          cards: ['Celebi ex'],
        },
        {
          rarity: Rarity.STAR2,
          probability: 0.5,
          cards: [
            'Celebi ex',
            'Gyarados ex',
            'Mew ex',
            'Aerodactyl ex',
            'Pidgeot ex',
            'Blue',
            'Budding Expeditioner',
            'Leaf',
            'Mew ex',
            'Aerodactyl ex',
          ],
        },
        {
          rarity: Rarity.STAR1,
          probability: 2.572,
          cards: [
            'Exeggutor',
            'Serperior',
            'Salandit',
            'Vaporeon',
            'Dedenne',
            'Marshadow',
          ],
        },
        {
          rarity: Rarity.DIAMOND4,
          probability: 1.666,
          cards: [
            'Celebi ex',
            'Gyarados ex',
            'Mew ex',
            'Aerodactyl ex',
            'Pidgeot ex',
          ],
        },
        {
          rarity: Rarity.DIAMOND3,
          probability: 5.0,
          cards: [
            'Mew',
            'Serperior',
            'Volcarona',
            'Vaporeon',
            'Raichu',
            'Golem',
            'Marshadow',
            'Tauros',
          ],
        },
        {
          rarity: Rarity.DIAMOND2,
          probability: 90,
          cards: [
            'Exeggutor',
            'Servine',
            'Shiinotic',
            'Dhelmise',
            'Rapidash',
            'Magmar',
            'Lumineon',
            'Drednaw',
            'Electabuzz',
            'Galvantula',
            'Sigilyph',
            'Florges',
            'Beheeyem',
            'Graveler',
            'Stonjourner',
            'Weezing',
            'Scolipede',
            'Druddigon',
            'Mythical Slab',
            'Pokémon Flute',
            'Blue',
            'Budding Expeditioner',
            'Leaf',
          ],
        },
      ],
    },
    {
      order: Order.FIFTH,
      bundles: [
        {
          rarity: Rarity.CROWN,
          probability: 0.16,
          cards: ['Mew ex'],
        },
        {
          rarity: Rarity.STAR3,
          probability: 0.888,
          cards: ['Celebi ex'],
        },
        {
          rarity: Rarity.STAR2,
          probability: 2.0,
          cards: [
            'Celebi ex',
            'Gyarados ex',
            'Mew ex',
            'Aerodactyl ex',
            'Pidgeot ex',
            'Blue',
            'Budding Expeditioner',
            'Leaf',
            'Mew ex',
            'Aerodactyl ex',
          ],
        },
        {
          rarity: Rarity.STAR1,
          probability: 10.288,
          cards: [
            'Exeggutor',
            'Serperior',
            'Salandit',
            'Vaporeon',
            'Dedenne',
            'Marshadow',
          ],
        },
        {
          rarity: Rarity.DIAMOND4,
          probability: 6.664,
          cards: [
            'Celebi ex',
            'Gyarados ex',
            'Mew ex',
            'Aerodactyl ex',
            'Pidgeot ex',
          ],
        },
        {
          rarity: Rarity.DIAMOND3,
          probability: 20,
          cards: [
            'Mew',
            'Serperior',
            'Volcarona',
            'Vaporeon',
            'Raichu',
            'Golem',
            'Marshadow',
            'Tauros',
          ],
        },
        {
          rarity: Rarity.DIAMOND2,
          probability: 90,
          cards: [
            'Exeggutor',
            'Servine',
            'Shiinotic',
            'Dhelmise',
            'Rapidash',
            'Magmar',
            'Lumineon',
            'Drednaw',
            'Electabuzz',
            'Galvantula',
            'Sigilyph',
            'Florges',
            'Beheeyem',
            'Graveler',
            'Stonjourner',
            'Weezing',
            'Scolipede',
            'Druddigon',
            'Mythical Slab',
            'Pokémon Flute',
            'Blue',
            'Budding Expeditioner',
            'Leaf',
          ],
        },
      ],
    },
  ],
};

const pikachuPacket: Packet = {
  name: PacketName.PIKACHU,
  subPackets: [],
};

export const packets = [mewPacket, pikachuPacket];
