export const popularBuildUps = [
  {
    name: 'Fire Blitz Deck',
    cards: [
      'Charizard GX',
      'Blaziken V',
      'Heatran GX',
      'Reshiram & Charizard GX',
      'Victini V',
      'Volcanion Prism Star',
      'Flareon',
      'Infernape',
      'Delphox',
      'Typhlosion',
      'Torkoal',
      'Magcargo',
      'Rapidash',
      'Salazzle',
      'Rotom Heat',
      'Arcanine',
      'Cinderace',
      'Houndoom',
      'Ninetales',
      'Simisear',
    ],
  },
  {
    name: 'Water Surge Deck',
    cards: [
      'Blastoise GX',
      'Lapras VMAX',
      'Kyogre EX',
      'Gyarados',
      'Palkia & Dialga GX',
      'Suicune V',
      'Kingdra',
      'Empoleon',
      'Feraligatr',
      'Lanturn',
      'Walrein',
      'Seismitoad',
      'Swampert',
      'Clawitzer',
      'Primarina',
      'Dewgong',
      'Pelipper',
      'Octillery',
      'Lumineon',
      'Crawdaunt',
    ],
  },
];
